### ISSUE TITLE
How to train a model?

### ISSUE THREAD

**Issue by ThePassedWind** [nihalsid/panoptic-lifting#14]
Hi~
After I succeeded in running inference command, I tried your **commands of training models**:
1. python trainer/train_panopli_tensorf.py experiment=scannet042302 wandb_main=True batch_size=4096 dataset_root="data/scannet/scene0423_02/"
2. python trainer/train_panopli_tensorf.py experiment=replicaroom0 wandb_main=True batch_size=4096 dataset_root="data/replica/room_0/" lambda_segment=0.75
3. python trainer/train_panopli_tensorf.py experiment=hypersim001008 wandb_main=True dataset_root="data/hypersim/ai_001_008/" lambda_dist_reg=0 val_check_interval=1 instance_optimization_epoch=4 batch_size=2048 max_epoch=34 late_semantic_optimization=4 segment_optimization_epoch=24 bbox_aabb_reset_epochs=[2,4,8] decay_step=[16,32,48] grid_upscale_epochs=[2,4,8,16,20] lambda_segment=0.5
4. python trainer/train_panopli_tensorf.py experiment=itw_office0213meeting_andram wandb_main=True batch_size=8192

However, all of them failed and the same error is:
Traceback (most recent call last):
  File "trainer/train_panopli_tensorf.py", line 335, in main
    trainer = create_trainer("PanopLi", config)
  File "xxx/panoptic-lifting/./trainer/__init__.py", line 110, in create_trainer
    trainer = Trainer(devices=[0],
  File "xxx/envs/panoptic/lib/python3.8/site-packages/pytorch_lightning/utilities/argparse.py", line 69, in insert_env_defaults
    return fn(self, **kwargs)
**TypeError: __init__() got an unexpected keyword argument 'resume_from_checkpoint'**

Could you help me solve this problem?

**Comment by nihalsid** [comment]
Seems to me like a pytorch lightning issue, perhaps they deprecated resume_from_checkpoint? Can you check the documentation? (quick look seems to suggest it is `ckpt_path` instead of `resume_from_checkpoint` now).

**Comment by nihalsid** [comment]
Perhaps just use the same old pytorch-lightning version as in the requirements.txt -- pl seems to have changed how to specify resume dirs
