### ISSUE TITLE
About the  implement of blocking semantics-to-geometry gradients.

### ISSUE THREAD

**Issue by DonVColreone** [nihalsid/panoptic-lifting#17]
HI, thank for sharing such an amazing work.  Could you share about how to implement blocking the gradients in this  code？Because it seems that  the gradient backward graph are not interrupted between semantic MLP and geometry network by some ops like ’detach‘.
Thanks.

**Comment by nihalsid** [comment]
Hi! We have this gradient block here: https://github.com/nihalsid/panoptic-lifting/blob/7af7a3e8477ead8e57f699a240d993e3bc21ee42/model/renderer/panopli_tensoRF_renderer.py#L126
