### ISSUE TITLE
About the injective mapping.

### ISSUE THREAD

**Issue by yokinglou** [nihalsid/panoptic-lifting#21]
Hi, 

I'm a little confused about the injective mapping $\Pi_I$ after reading the Instance Loss paragraph. I could not find more details about it in the paper. Could you please explain the objective or definition of this mapping?

Thx for your excellent work!

**Comment by nihalsid** [comment]
Hi Yoking! Thank you for the issue, can you check the discussion here helps:
https://github.com/nihalsid/panoptic-lifting/issues/11 

If this doesnt help, please let me know, happy to discuss it in more detail here if needed.
