### ISSUE TITLE
Creating custom dataset

### ISSUE THREAD

**Issue by XinyangHan** [nihalsid/panoptic-lifting#23]
Great work!!! May I ask for some tips to process the custom dataset? E.g. to substitute some labels, run specific scipt?

**Comment by akshay-krishnan** [comment]
+1, I could use some instructions to run it on a different dataset too. The code in PanopLiDataset seems specific to the datasets used in the work.

**Comment by nihalsid** [comment]
Hi Xinyang/Akshay, try out this file: [preprocess_itw](https://github.com/nihalsid/panoptic-lifting/tree/main/dataset/preprocessing/preprocess_itw.py), you'll have to follow the steps there in comments (especially at what point to have mask2former ready). For mask2former please use our fork specified in the readme. Let me know if you get any issues.

**Comment by engrkhurramshabbir** [comment]
Thanks a lot for sharing the great work. Code demo.py successfully got executed but there are no output images in the output folder.  

  0%|                                                                                                                                                                     | 0/2 [00:00<?, ?it/s]/home/khurram/anaconda3/envs/detectron2/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1678402374358/work/aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
TTA Handler time: 105.75s
[12/05 02:04:13 detectron2]: input/input1.jpg: finished in 108.63s
Saving output to: output/input1.jpg
 50%|██████████████████████████████████████████████████████████████████████████████                                                                              | 1/2 [01:48<01:48, 108.64s/it]TTA Handler time: 149.68s
[12/05 02:06:49 detectron2]: input/input2.jpg: finished in 155.46s
Saving output to: output/input2.jpg
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [04:24<00:00, 132.06s/it]

My input command is as follows:
 python demo/demo.py --config-file /media/khurram/9826FFCA26FFA780/NeRF/mask2former/mask2former/configs/coco/panoptic-segmentation/maskformer2_R50_bs16_50ep.yaml   --input input --output output
