### ISSUE TITLE
Hypersim Scene Split

### ISSUE THREAD

**Issue by ChenLu-china** [nihalsid/panoptic-lifting#24]
Hi @nihalsid , 

Thanks for your great work. I notice that you select 63 frames from 200 images of scene ai_008_004. Can you publish the index frames and split strategy?

**Comment by nihalsid** [comment]
Hi, for hypersim I was using the script [preprocess_hypersim.py](https://github.com/nihalsid/panoptic-lifting/blob/main/dataset/preprocessing/preprocess_hypersim.py). IIRC for this particular scene there were some cameras that were out of bounds of the physical room and contributing too little to the objects in focus, so we just removed them. The split is just random out of the remaining views.

**Comment by ChenLu-china** [comment]
> 

Thanks for your reply!
