### ISSUE TITLE
Training and testing config of the model report in the Paper

### ISSUE THREAD

**Issue by Binyr** [nihalsid/panoptic-lifting#28]
Dear author:
It's a very nice work to attract me!

I find that config.yaml in your scannet pretrained model use image_dim 256 while the panopli.yaml use image_dim 512. Besides, inference/evaluate.py use image_dim 512?

I wonder know which is your train / test confg file. 
Thank you!

**Comment by nihalsid** [comment]
Hi Binyr, thank you for your interest in the work, the scannet models were trained at a resolution of 256 iirc for fast convergance and then finetuned at a resolution of 512. Inference is always done at 512.
