### ISSUE TITLE
Can not reproduce the performance on scannet

### ISSUE THREAD

**Issue by Binyr** [nihalsid/panoptic-lifting#30]
Hi @nihalsid, this is really interesting work!

When I tried to train a model for scannet scene0693_00,I got a much worse performance (IoU: 0.572) than the pretrained model (mIoU: 0.673) you provided for this scene. 
I used the config.yaml file  in the pretrained model (https://drive.google.com/file/d/1KsIq4MBIDIa08gREoRWePI0qXYJE_4HW/view). Training command is :
<python trainer/train_panopli_tensorf.py experiment=scannet069300 dataset_root=data/scannet/scene0693_00 max
_rays_segments=512>

I understand that re-training the models might take time. However, if you can provide the hyperparameters you used for each scene in Scannet, that would also be quite helpful.

**Comment by chenghao-li-1029** [comment]
@Binyr Hi, any update? I'm reimplementing panoptic-lifting, and the mIoU scores are lower than the reported ones in Hypersim, Repica, and Scannet (0423). Wondering if there is something I missed.

**Comment by Binyr** [comment]
> @Binyr Hi, any update? I'm reimplementing panoptic-lifting, and the mIoU scores are lower than the reported ones in Hypersim, Repica, and Scannet (0423). Wondering if there is something I missed.

not yet

**Comment by nihalsid** [comment]
Hi, yes the config.yaml of pretrained model should work. However, you'd have to finish the training to the end of all the specified epochs (15 or so). It also helps if after the epoch ~12 resolution is increased to 512
