### ISSUE TITLE
panoptic-lifting/inference/render_panopli.py, line 13, in <module>  error

### ISSUE THREAD

**Issue by kenan9875645** [nihalsid/panoptic-lifting#31]
Hi!I have encountered some problems. When I run the following command:
Python inference/render_ Panopli.py pre trained examples/typim_ Ai001008/checkpoint/epoch=30 step=590148.ckpt False

Error: Traceback (most recent call last):
File "/home/homi/NERF/panoptical changing/reference/render_panopli. py", line 13, in<module>
From dataset import PanopLiDataset, create_ Segmentation_ Data_ Panopli
ModuleNotFoundError: No module named 'dataset'

And when I pip install dataset, I run the command: Python conference/render_ Panopli.py pre trained examples/typim_ Ai001008/checkpoint/epoch=30 step=590148.ckpt False

An error will be reported:
Traceback (most recent call last):
File "/home/homi/NERF/panoptic changing/reference/render_panopli. py", line 13, in<module>
From dataset. panopli import PanopLiDataset, create_ Segmentation_ Data_ Panopli
ModuleNotFoundError: No module named 'dataset. panopli'

May I ask how to solve it?

**Comment by sangminkim-99** [comment]
You can add your working directory to the environment variable `PYTHONPATH`.
It can be done by `export PYTHONPATH=$(pwd):$PYTHONPATH`.
Ref: https://stackoverflow.com/questions/23417941/import-error-no-module-named-does-exist

**Comment by kenan9875645** [comment]
> You can add your working directory to the environment variable `PYTHONPATH`. It can be done by `export PYTHONPATH=$(pwd):$PYTHONPATH`. Ref: https://stackoverflow.com/questions/23417941/import-error-no-module-named-does-exist

Thank you very much！
