### ISSUE TITLE
'output_instances' does not contribute to the loss calculation during the 'training_step

### ISSUE THREAD

**Issue by Francisco-liu** [nihalsid/panoptic-lifting#35]
Hi! I am having difficulty understanding the reason behind this; specifically, 'output_instances' does not contribute to the loss calculation during the 'training_step,' but it is utilized to generate instance segmentation results in the 'validation_step' stage. Could you please explain the rationale for this? Thank you very much.

**Comment by nihalsid** [comment]
Hi, instances are optimized here in the lines https://github.com/nihalsid/panoptic-lifting/blob/b8ad4f5941ed0158f365d2c19facc86fbae2061e/trainer/train_panopli_tensorf.py#L177C9-L177C74
