### ISSUE TITLE
how to create coco_to_scannet.csv file?

### ISSUE THREAD

**Issue by annabasiljose1** [nihalsid/panoptic-lifting#38]
Hey! Impressive work. Can you please give some guidelines on how you created the files coco_to_scannet_reduced.csv and scannet_extended_to_coco.csv? How should I proceed if I want to create similar files for a custom dataset that closely resembles the Cityscapes dataset?
Thanks in advance!

**Comment by nihalsid** [comment]
Hi,

Thanks! You have to manually create this depending on which classes remap
from your dataset to coco.

Regards,
Yawar Nihal
