### ISSUE TITLE
[Running on the custom dataset] Hi! How can I run this on my personally gathered dataset?!

### ISSUE THREAD

**Issue by idra79haza** [nihalsid/panoptic-lifting#8]
Hi! Thank you for the great work!!! I am really impressed!!

I want to run your program on my personal gathered dataset from Azure Kinect?

Can you share your idea towards how to do it!?

Thank you in advance!

**Comment by nihalsid** [comment]
Hi, thank you so much!

Please check out the itw (in the wild) and self-captured instructions in the readme. Basically there are two parts to datapreprocessing:

1) Running mask2former (Use this fork for test time augmented version: https://github.com/nihalsid/mask2former)
2) Running the preprocessing scripts (https://github.com/nihalsid/panoptic-lifting/blob/main/dataset/preprocessing/preprocess_itw.py)

Let me know if you get stuck with any particular step.

Thanks,
Yawar
